[package]
name = "rust-seal"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
oqs = { version = "0.11.0", features = ["serde"] }
tempfile = "3.20.0"
